language: java
jdk:
  - openjdk11
dist: xenial
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: gateway-chatapp
before_install:
  - ./mvnw clean package -DskipTests=true -Dmaven.javadoc.skip=true -Dspring.profiles.active=$ENVIRONMENT -e